services:
  app:
    build: .
    container_name: library_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - library-net

  db:
    image: postgres:15
    container_name: library_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - library-data:/var/lib/postgresql/data
    networks:
      - library-net

volumes:
  library-data:

networks:
  library-net:
