ALTER TABLE comments DROP CONSTRAINT IF EXISTS fk_comment_user;
ALTER TABLE comments DROP CONSTRAINT IF EXISTS fk_comment_book;

ALTER TABLE books DROP CONSTRAINT IF EXISTS fk_books_author;

DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS users;
